project:
  type: website

website:
  title: "Сайт преподавателя"
  navbar:
    logo: images/logo.jpg
    background: primary
    search: true
    right: 
      - href: stud_work.qmd
        text: "Работы студентов"
      - href: cv.qmd
        text: "CV"
      - href: publications.qmd
        text: "Публикации"

format:
  html:
    page-layout: full
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

