project:
  type: website

website:
  title: "Сайт преподавателя"
  navbar:
    logo: images/logo.jpg
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - href: stud_work.qmd
        text: "Работы студентов"
      - href: cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

