---
title: "Шутова Ольга Анатольевна"
---

-   электронный адрес: oa.shoutova\@physics.msu.ru

-   13 сентября 1977 г.р.

-   кандидат физико-математических наук

-   ассистент кафедры общей физики и волновых процессов физического факультета МГУ им. М.В. Ломоносова

-   Образование:

    -   1994 г. окончание специализированного учебно-научного центра МГУ им. М.В. Ломоносова (СУНЦ МГУ, школа им. А.Н. Колмогорова);

    -   2000 г. окончание физического факультета МГУ им. М.В. Ломоносова (диплом с отличием);

    -   2006 г. окончание аспирантуры физического факультета МГУ им. М.В. Ломоносова (защищена кандидатская диссертация на тему: «Взаимодействие сильного электромагнитного поля с одиночным атомом и средой в рамках непертурбативной теории: нарушение традиционной симметрии задачи»).

-   Повышение квалификации:

    -   2020 г. на философском факультете МГУ имени М.В. Ломоносова курс "Цифровая педагогика в современном универститете" (диплом).

-   Наукометрические данные:

    -   [Профиль на сайте МГУ](https://istina.msu.ru/profile/ShoutovaOA/).

    -   Количество статей за все время: 35.

    -   Количество цитирований статей в журналах по данным Web of Science: 75, Scopus: 82

-   Опыт преподавательской работы:

    -   Лекции по курсу: "Введение в нанооптику" (МГУ им. М.В.Ломоносова, физический факультет, 4-ый курс, совместно с доц. Коновко А.А.)
    -   Лекции по курсу: "Современная оптическая микроскопия сверхвысокого разрешения" (МГУ им. М.В.Ломоносова, физический факультет, магистранты, 1-й год обучения)
    -   Лекции по курсу: "Атомные частицы в сильных световых полях" (МГУ им. М.В.Ломоносова, физический факультет, магистранты, 1-й год обучения)
    -   Семинары по курсу "Термодинамика и статистическая физика" (МГУ им. М.В.Ломоносова, факультет ВМиК, 3-ий курс)
    -   Семинары по курсу "Физика волновых процессов" (МГУ им. М.В.Ломоносова, факультет ВМиК, 3-ий курс)
