---
title: "Публикации"
editor: visual
---

## Физический факультет

**2019:**

[Мария Князева "Фаза Берри" ](https://drive.google.com/open?id=1zp_YlE6kxMpEPTT464lW_40M9nASRW5b)

**2018:**

[Павел Глек "Фокусировка оптического излучения: векторная теория Дебая и фазовые элементы"](https://drive.google.com/open?id=1tibxQiK7agS82i4Y1w2mJic5UKL2MVXF)

[Платон Рыжиков "Визуализация решения Бёте-Баукампа для прохождения света через малое отверстие"](https://drive.google.com/open?id=1iKYySd8MajvdFIvk6SPaNc2bQyKDiwGW)

**2017**:

[Г. Господинов "Радиофизические методы в оптике"](https://drive.google.com/open?id=1C44IUQgLZZZZFMYrxcPIASsUcpEZs3-i)

[Н. Петров "Нарушенное полное внутреннее отражение"](https://drive.google.com/open?id=0B8E725UDr12PRkFZMnlycFYzcVE)

**2016:**

[Н. Кузнецов "Фазово-контрастная микроскопия Цернике"](https://drive.google.com/open?id=0B8E725UDr12POXZaTUNkUVRIeGs)

[М. Рожко "Нобелевская лекция Штефана Хелля"](https://drive.google.com/open?id=0B8E725UDr12PenRIaVBvUGl6d2M)

[Г. Мартынов "Дифракционный предел Аббе и разрешающая способность оптических систем"](https://drive.google.com/open?id=0B8E725UDr12PSVRLallmYndBSnFJSGpxUTRCdmpzTTlPXy1j)

**2015:**

[А. В. Пушкин "Фазово-контрастная микроскопия"](https://drive.google.com/file/d/0B8E725UDr12PWlpBR2E3YzJDbnc/view?usp=sharing)

[Е. Мигаль "Векторные пучки"](https://drive.google.com/file/d/0B8E725UDr12Pd2JxQklhMWF2VTg/view?usp=sharing)

[E. Фельдман "Микроскопия на основе TERS/SERS"](https://drive.google.com/file/d/0B8E725UDr12PZ09Md21jb1lfQVE/view?usp=sharing)

[А. Сидоров "Методы создания зондов для ближнепольной микроскопии"](https://drive.google.com/file/d/0B8E725UDr12PSEg2Mk9BTlFOS1U/view?usp=sharing)

## Факультет ВМК 

Колебания в цепочке чередующихся масс ([работа Дарьи Гавриловой, 2019 г.](https://drive.google.com/file/d/1rayTkwRDzdiAuIpJG5AzFAauobTTulY8/view?usp=sharing)).

Презентация студента 302 гр. Колотова Антона по двойной антенной линейке [смотреть](https://drive.google.com/file/d/1FJnZfSlKQcAzaOTJWl0on_-z2gFe7Oma/view?usp=sharing).

Презентация студента 302 гр. Величкина Матвея по дифракции на квадратном отверстии [смотреть](https://drive.google.com/file/d/10TU6Y5SialbqzlhzSOFm4cqwFQ1PJ9-1/view?usp=sharing).

**Спектры:**

**2020:**

Презентация студента 302 гр. Величкина Матвея по дискретному Фурье преобразованию [смотреть](https://drive.google.com/file/d/1E9AwCstaeJ1Jt2D9kpI9oS_tnVsx7xT7/view?usp=sharing).

Презентации студентки 307 гр. Смирновой Эльзы [1-ю смотреть](https://drive.google.com/file/d/12r5eYdagZ510waiHsbZYcJ7uH9JUROSn/view?usp=sharing), [2-ю смотреть.](https://drive.google.com/file/d/1PrcPYoTesg3mgu1qBTDa63Wva8t7lPJc/view?usp=sharing)

Презентация студента 302 гр. Колотова Антона [смотреть](https://drive.google.com/file/d/1gd_a5v4JfpYJFlJSajyd44J5LYy5o5JB/view?usp=sharing).

Презентация студента 303 гр. Рыгина Антона [смотреть](https://drive.google.com/file/d/17fzOGYEbfkOsar6h8Q59bBZkeqrtKmqb/view?usp=sharing).

Презентации студента 303 гр. Мордвинцева Михаила [1-ю смотреть](https://drive.google.com/file/d/1rdqiRBD6nd61HF4M5rnfJGQ34d9Md_zn/view?usp=sharing), [2-ю смотреть](https://drive.google.com/file/d/1DrcC5R4dPo_X2xyGjaKo_P8scD0ntV8M/view?usp=sharing).

Презентация студента 303 гр. Михайлова Арсения [смотреть](https://drive.google.com/file/d/15itQ-3GGjUwqqwJ9Z7qHH5zYEptTA-s1/view?usp=sharing).

Презентация студентки 302 гр. Дарьи Разживиной [смотреть](https://drive.google.com/file/d/19ejcfPO50WmaA5XJljhKpqayfyggjHfE/view?usp=sharing).

**2019:**

[Работа студентки гр.301 Гавриловой Дарьи](https://drive.google.com/file/d/1qOi-EXZ6eyDk-Kk_UjppP3XryeDmP0Y6/view?usp=sharing)

[Работа студента гр.303 Чижикова Алексея](https://drive.google.com/open?id=1UYLEks_PtGfKbzkdI0hD3SvdMd-1TqGu)

[Работа студента гр. 303 Чижова Петра](https://drive.google.com/file/d/1hiSjUyeM3b9Fc8B2MFcEnOj3-L4b7H7g/view?usp=sharing)

[Работы студентов ВМК МГУ им. М.В. Ломоносова по куру: Термодинамика и статистическая физика](http://www.google.com/url?q=http%3A%2F%2Fcmcstatphys.ilc.edu.ru%2F&sa=D&sntz=1&usg=AOvVaw1BTWcIlEURUycCzjoxb98v)

Факультет космических исследований

**2020**:

[Александр Петров "Исследование колебаний математическогомаятника с нитью переменной длины"](https://drive.google.com/file/d/1qClwkExDW2cEL8MqCHI1mgMuES556AXd/view?usp=sharing)
